import puppeteer from "puppeteer";

export async function generateHtmlPdf(order: any) {
  // 1. Browser starten (headless = unsichtbar)
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"], // Wichtig für manche Server
  });
  const page = await browser.newPage();

  // 2. Deine Daten für das Template vorbereiten
  const itemsHtml = order.items
    .map(
      (item: any, index: number) => `
      <tr class="item-row">
        <td>${index + 1}</td>
        <td>${item.products?.name ?? "Unknown"}</td>
        <td>${item.color}</td>
        <td>${item.size}</td>
        <td>${item.quantity}</td>
      </tr>
    `
    )
    .join("");

  // 3. Das HTML/CSS Template (Hier kannst du dich austoben!)
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 40px; border-bottom: 2px solid #000; padding-bottom: 20px; }
        .title { font-size: 24px; font-weight: bold; text-transform: uppercase; }
        .meta { text-align: right; font-size: 14px; line-height: 1.6; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { text-align: left; background: #f4f4f4; padding: 10px; border-bottom: 1px solid #ddd; }
        td { padding: 10px; border-bottom: 1px solid #eee; }
        .item-row:nth-child(even) { background-color: #f9f9f9; }
        
        .footer { margin-top: 50px; font-size: 12px; color: #777; text-align: center; border-top: 1px solid #eee; padding-top: 20px;}
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">Production Sheet</div>
        <div class="meta">
          <strong>Order ID:</strong> ${order.id.slice(0, 8)}<br>
          <strong>Date:</strong> ${new Date(order.created_at).toLocaleDateString()}<br>
          <strong>Status:</strong> ${order.status.toUpperCase()}
        </div>
      </div>

      <div style="margin-bottom: 20px;">
        <strong>Customer:</strong> ${order.customer_name}
      </div>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Product</th>
            <th>Color</th>
            <th>Size</th>
            <th>Qty</th>
          </tr>
        </thead>
        <tbody>
          ${itemsHtml}
        </tbody>
      </table>

      <div class="footer">
        Generated by Miktool Automation
      </div>
    </body>
    </html>
  `;

  // 4. HTML in den Browser laden und als PDF drucken
  await page.setContent(htmlContent);
  const pdfBuffer = await page.pdf({ format: "A4", printBackground: true });

  await browser.close();
  return pdfBuffer;
}